os:
  - linux
    # Deactivated OSX. Same issue happened to other python projects on OSX.
    # https://github.com/jkbrzt/httpie/commit/8eb460a6f3925a6020020bf412ccec7342294a60
    #  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install xclip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install black
script:
  - python setup.py test
  - black --check .
after_success:
  - coveralls
